# This is a basic workflow to help you get started with Actions
name: Build and Deploy Hugo Site

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  Build_and_Deploy:
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout
          uses: actions/checkout@v2

        # Sets up Hugo
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
              hugo-version: '0.94.2'

        # Builds website repo
        - name: Build
          run: hugo -e development -b https://mappjzc.github.com/
        - name: Deploy
          uses: benmatselby/hugo-deploy-gh-pages@master
          env:
            GITHUB_ACTOR: mappjzc
            HUGO_VERSION: '0.94.2+extended'
            TARGET_REPO: mappjzc/mappjzc.github.io
            TARGET_BRANCH: main
            TOKEN: ${{ secrets.DEVLAKE_WEBSITE }}
            CNAME: mappjzc.github.io